# python-ci.yml
name: basic CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-run-pytest:

    runs-on: ubuntu-latest

    steps:
      # 1. checkout to the branch that triggered the event
      # https://github.com/actions/checkout
    - uses: actions/checkout@v3

      # 2. install python 3.10
      # https://github.com/actions/setup-python
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

      # 3. install python packages using a requirements file
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip cython wheel
        pip install -r requirements.txt

      # 4. run tests with Pytest, according to our Makefile
    - name: Run tests
      run: make